import { Sparkles, CheckCircle2, AlertTriangle, ArrowRight } from "lucide-react";
import type { AiExplanation } from "@/services/scanService";
import { cn } from "@/utils/cn";

interface AiExplanationCardProps {
  explanation: AiExplanation;
}

/**
 * Beginner-friendly explanation of the scan, generated by Claude (or
 * a rule-based fallback — see server/src/services/aiExplanation.ts).
 * Deliberately styled differently from ScanResultCard: a soft gradient
 * border and a "Sparkles" badge mark this out as the AI's read on the
 * report rather than another raw check.
 */
export function AiExplanationCard({ explanation }: AiExplanationCardProps) {
  const { verdict, reasons, risks, nextSteps, generatedByAi } = explanation;

  return (
    <div className="relative rounded-xl2 bg-cta-gradient/20 p-[1px]">
      <div className="rounded-xl2 bg-base-surface p-6 sm:p-7">
        <div className="flex items-center gap-2.5">
          <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-cta-gradient/15 ring-1 ring-inset ring-accent-primary/25">
            <Sparkles className="h-4 w-4 text-accent-secondary" />
          </div>
          <div>
            <h2 className="font-display text-sm font-semibold text-ink">AI Assistant</h2>
            <p className="text-[11px] text-ink-faint">
              {generatedByAi ? "Generated by Claude for this scan" : "Template-based summary"}
            </p>
          </div>
        </div>

        <p className="mt-4 text-base font-medium leading-relaxed text-ink">{verdict}</p>

        {reasons.length > 0 && (
          <ExplanationList
            heading="Why"
            items={reasons}
            icon={CheckCircle2}
            iconClassName="text-accent-secondary"
          />
        )}

        {risks.length > 0 ? (
          <ExplanationList
            heading="Risks found"
            items={risks}
            icon={AlertTriangle}
            iconClassName="text-accent-warning"
          />
        ) : (
          <p className="mt-5 text-sm text-ink-muted">No specific risks were found in this scan.</p>
        )}

        {nextSteps.length > 0 && (
          <ExplanationList
            heading="What to do next"
            items={nextSteps}
            icon={ArrowRight}
            iconClassName="text-accent-primary"
          />
        )}
      </div>
    </div>
  );
}

function ExplanationList({
  heading,
  items,
  icon: Icon,
  iconClassName,
}: {
  heading: string;
  items: string[];
  icon: typeof CheckCircle2;
  iconClassName?: string;
}) {
  return (
    <div className="mt-5">
      <h3 className="text-xs font-semibold uppercase tracking-wide text-ink-faint">{heading}</h3>
      <ul className="mt-2.5 flex flex-col gap-2">
        {items.map((item, index) => (
          <li key={index} className="flex items-start gap-2.5 text-sm leading-relaxed text-ink-muted">
            <Icon className={cn("mt-0.5 h-4 w-4 shrink-0", iconClassName)} />
            <span>{item}</span>
          </li>
        ))}
      </ul>
    </div>
  );
}
