import { Sparkles, Info, AlertTriangle, ArrowRight } from "lucide-react";
import type { ResumeAiReview } from "@/services/resumeScanService";
import { cn } from "@/utils/cn";

interface ResumeAiReviewCardProps {
  review: ResumeAiReview;
}

/**
 * Beginner-friendly privacy review, generated by Claude (or a
 * rule-based fallback — see server/src/services/resumeAiReview.ts).
 * Styled to match AiExplanationCard (Website Scanner) for visual
 * consistency across CyberSentinel's two AI review surfaces.
 */
export function ResumeAiReviewCard({ review }: ResumeAiReviewCardProps) {
  const { summary, foundInfo, risks, recommendations, generatedByAi } = review;

  return (
    <div className="relative rounded-xl2 bg-cta-gradient/20 p-[1px]">
      <div className="rounded-xl2 bg-base-surface p-6 sm:p-7">
        <div className="flex items-center gap-2.5">
          <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-cta-gradient/15 ring-1 ring-inset ring-accent-primary/25">
            <Sparkles className="h-4 w-4 text-accent-secondary" />
          </div>
          <div>
            <h2 className="font-display text-sm font-semibold text-ink">AI Privacy Review</h2>
            <p className="text-[11px] text-ink-faint">
              {generatedByAi ? "Generated by Claude for this resume" : "Template-based summary"}
            </p>
          </div>
        </div>

        <p className="mt-4 text-base font-medium leading-relaxed text-ink">{summary}</p>

        {foundInfo.length > 0 && (
          <ReviewList heading="What was found" items={foundInfo} icon={Info} iconClassName="text-accent-primary" />
        )}

        {risks.length > 0 ? (
          <ReviewList heading="Potential risks" items={risks} icon={AlertTriangle} iconClassName="text-accent-warning" />
        ) : (
          <p className="mt-5 text-sm text-ink-muted">No specific privacy risks stood out in this review.</p>
        )}

        {recommendations.length > 0 && (
          <ReviewList
            heading="What to consider"
            items={recommendations}
            icon={ArrowRight}
            iconClassName="text-accent-secondary"
          />
        )}
      </div>
    </div>
  );
}

function ReviewList({
  heading,
  items,
  icon: Icon,
  iconClassName,
}: {
  heading: string;
  items: string[];
  icon: typeof Info;
  iconClassName?: string;
}) {
  return (
    <div className="mt-5">
      <h3 className="text-xs font-semibold uppercase tracking-wide text-ink-faint">{heading}</h3>
      <ul className="mt-2.5 flex flex-col gap-2">
        {items.map((item, index) => (
          <li key={index} className="flex items-start gap-2.5 text-sm leading-relaxed text-ink-muted">
            <Icon className={cn("mt-0.5 h-4 w-4 shrink-0", iconClassName)} />
            <span>{item}</span>
          </li>
        ))}
      </ul>
    </div>
  );
}
