import PDFDocument from "pdfkit";
import type { SecurityReportData } from "../types";

const BRAND_COLOR = "#4F7CFF";
const MUTED_COLOR = "#5B6479";
const INK_COLOR = "#1A2233";

/**
 * Same pdfkit architecture as resumePdfExport.ts, emailPdfExport.ts,
 * and passwordPdfExport.ts — this is a new content layout, not a new
 * PDF-generation system. Deliberately never includes passwords,
 * leaked credentials, raw breach data, or anything beyond what the
 * report data itself already summarizes.
 */
export function generateSecurityReportPdf(report: SecurityReportData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 50 });
    const chunks: Buffer[] = [];

    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.fillColor(BRAND_COLOR).fontSize(20).font("Helvetica-Bold").text("CyberSentinel");
    doc.fillColor(MUTED_COLOR).fontSize(10).font("Helvetica").text("Security Report");
    doc.moveDown(0.5);
    doc.fillColor(MUTED_COLOR).fontSize(9).font("Helvetica").text(`Generated ${new Date(report.generatedAt).toLocaleString()}`);
    doc.text(`Period: ${report.timeRangeLabel}`);
    doc.moveDown(1);

    doc
      .fillColor(BRAND_COLOR)
      .fontSize(26)
      .font("Helvetica-Bold")
      .text(report.overallScore !== null ? `${report.overallScore}/100` : "Not enough data yet", {
        continued: report.grade !== null,
      })
      .fillColor(MUTED_COLOR)
      .fontSize(12)
      .font("Helvetica");
    if (report.grade !== null) doc.text(`   Grade: ${report.grade}`);
    doc.moveDown(1);

    section(doc, "Category Scores");
    for (const category of report.categories) {
      doc
        .fillColor(INK_COLOR)
        .fontSize(10)
        .font("Helvetica-Bold")
        .text(`${category.title}: `, { continued: true })
        .font("Helvetica")
        .fillColor(MUTED_COLOR)
        .text(category.hasData ? `${category.score}/100` : "No data yet");
    }
    doc.moveDown(1);

    section(doc, "Major Findings");
    if (report.majorFindings.length === 0) {
      doc.fillColor(MUTED_COLOR).fontSize(10).font("Helvetica").text("No major findings for this period.");
    } else {
      for (const finding of report.majorFindings) bullet(doc, finding);
    }
    doc.moveDown(1);

    section(doc, "Recommendations");
    for (const rec of report.recommendations) {
      doc.fillColor(INK_COLOR).fontSize(10).font("Helvetica-Bold").text(`• ${rec.text}`);
      doc.fillColor(MUTED_COLOR).fontSize(9).font("Helvetica").text(rec.reason, { indent: 12 });
      doc.moveDown(0.3);
    }
    doc.moveDown(0.5);

    section(doc, "Learning Progress");
    doc
      .fillColor(MUTED_COLOR)
      .fontSize(10)
      .font("Helvetica")
      .text(
        `${report.learning.lessonsCompleted} lessons completed · Level ${report.learning.currentLevel} (${report.learning.levelTitle}) · ${report.learning.xpEarned} XP`
      );
    doc.moveDown(1);

    section(doc, "Threat Intelligence Activity");
    doc
      .fillColor(MUTED_COLOR)
      .fontSize(10)
      .font("Helvetica")
      .text(`${report.threatIntel.threatsViewed} threats viewed · ${report.threatIntel.threatsBookmarked} bookmarked`);
    doc.moveDown(1);

    section(doc, "Summary");
    doc.fillColor(INK_COLOR).fontSize(10).font("Helvetica").text(report.summary);

    doc.moveDown(1.5);
    doc
      .fillColor(MUTED_COLOR)
      .fontSize(8)
      .font("Helvetica")
      .text(
        "Generated by CyberSentinel — an educational security analytics summary, not a professional cybersecurity assessment.",
        { align: "center" }
      );

    doc.end();
  });
}

function section(doc: PDFKit.PDFDocument, title: string): void {
  doc.fillColor(BRAND_COLOR).fontSize(13).font("Helvetica-Bold").text(title);
  doc.moveDown(0.3);
}

function bullet(doc: PDFKit.PDFDocument, text: string): void {
  doc.fillColor(INK_COLOR).fontSize(10).font("Helvetica").text(`• ${text}`);
}
