import PDFDocument from "pdfkit";
import { EMAIL_CLASSIFICATION_LABELS } from "../utils/emailRiskScore";
import type { EmailAnalysisReport } from "../types";

const BRAND_COLOR = "#4F7CFF";
const MUTED_COLOR = "#5B6479";
const INK_COLOR = "#1A2233";

/** Renders an EmailAnalysisReport to a PDF buffer entirely in memory — mirrors resumePdfExport.ts. */
export function generateEmailReportPdf(report: EmailAnalysisReport): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 50 });
    const chunks: Buffer[] = [];

    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.fillColor(BRAND_COLOR).fontSize(20).font("Helvetica-Bold").text("CyberSentinel");
    doc.fillColor(MUTED_COLOR).fontSize(10).font("Helvetica").text("Email Phishing Analysis Report");
    doc.moveDown(1.5);

    doc
      .fillColor(MUTED_COLOR)
      .fontSize(9)
      .font("Helvetica")
      .text(`Analyzed ${new Date(report.analyzedAt).toLocaleString()}`);
    doc.moveDown(1);

    doc
      .fillColor(BRAND_COLOR)
      .fontSize(28)
      .font("Helvetica-Bold")
      .text(`${report.riskScore}/100`, { continued: true })
      .fillColor(MUTED_COLOR)
      .fontSize(12)
      .font("Helvetica")
      .text(`   ${EMAIL_CLASSIFICATION_LABELS[report.classification]}`);
    doc.moveDown(1);

    section(doc, "Summary");
    doc.fillColor(INK_COLOR).fontSize(10).font("Helvetica").text(report.aiExplanation.verdict);
    if (report.aiExplanation.risks.length > 0) {
      doc.moveDown(0.5);
      for (const risk of report.aiExplanation.risks) bullet(doc, risk);
    }
    doc.moveDown(1);

    section(doc, "Detected Indicators");
    if (report.indicators.length === 0) {
      doc.fillColor(MUTED_COLOR).fontSize(10).font("Helvetica").text("No suspicious indicators were detected.");
    } else {
      for (const indicator of report.indicators) {
        doc
          .fillColor(INK_COLOR)
          .fontSize(10)
          .font("Helvetica-Bold")
          .text(`${indicator.label} (${indicator.severity}): `, { continued: true })
          .font("Helvetica")
          .fillColor(MUTED_COLOR)
          .text(indicator.explanation);
      }
    }
    doc.moveDown(1);

    if (report.links.length > 0) {
      section(doc, "Extracted Links");
      for (const link of report.links) {
        doc.fillColor(INK_COLOR).fontSize(9).font("Helvetica").text(link.url);
      }
      doc.moveDown(1);
    }

    section(doc, "Recommendations");
    for (const step of report.aiExplanation.nextSteps) {
      doc.fillColor(INK_COLOR).fontSize(10).font("Helvetica-Bold").text(`• ${step}`);
      doc.moveDown(0.3);
    }

    doc.moveDown(1);
    doc
      .fillColor(MUTED_COLOR)
      .fontSize(8)
      .font("Helvetica")
      .text("Generated by CyberSentinel — an AI-powered cybersecurity assistant.", { align: "center" });

    doc.end();
  });
}

function section(doc: PDFKit.PDFDocument, title: string): void {
  doc.fillColor(BRAND_COLOR).fontSize(13).font("Helvetica-Bold").text(title);
  doc.moveDown(0.3);
}

function bullet(doc: PDFKit.PDFDocument, text: string): void {
  doc.fillColor(INK_COLOR).fontSize(10).font("Helvetica").text(`• ${text}`);
}
