import PDFDocument from "pdfkit";
import type { PasswordHistoryRecord } from "../types";

const BRAND_COLOR = "#4F7CFF";
const MUTED_COLOR = "#5B6479";
const INK_COLOR = "#1A2233";

const RATING_LABELS: Record<PasswordHistoryRecord["rating"], string> = {
  "very-weak": "Very Weak",
  weak: "Weak",
  fair: "Fair",
  strong: "Strong",
  excellent: "Excellent",
};

const CHECKLIST_LABELS: Record<keyof PasswordHistoryRecord["checklist"], string> = {
  uniquePasswords: "Uses unique passwords for each account",
  usesMfa: "Multi-factor authentication enabled",
  usesPasswordManager: "Uses a password manager",
  avoidsReuse: "Avoids reusing old passwords",
  checksForBreaches: "Regularly checks for data breaches",
};

/** Renders a PasswordHistoryRecord to a PDF buffer — never includes any password text, because none is ever stored. */
export function generatePasswordReportPdf(record: PasswordHistoryRecord): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 50 });
    const chunks: Buffer[] = [];

    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.fillColor(BRAND_COLOR).fontSize(20).font("Helvetica-Bold").text("CyberSentinel");
    doc.fillColor(MUTED_COLOR).fontSize(10).font("Helvetica").text("Password Security Report");
    doc.moveDown(1.5);

    doc.fillColor(MUTED_COLOR).fontSize(9).font("Helvetica").text(`Analyzed ${new Date(record.analyzedAt).toLocaleString()}`);
    doc.moveDown(1);

    doc
      .fillColor(BRAND_COLOR)
      .fontSize(28)
      .font("Helvetica-Bold")
      .text(`${record.score}/100`, { continued: true })
      .fillColor(MUTED_COLOR)
      .fontSize(12)
      .font("Helvetica")
      .text(`   ${RATING_LABELS[record.rating]}`);
    doc.moveDown(1);

    doc.fillColor(BRAND_COLOR).fontSize(13).font("Helvetica-Bold").text("Recommendations");
    doc.moveDown(0.3);
    for (const rec of record.recommendations) {
      doc.fillColor(INK_COLOR).fontSize(10).font("Helvetica").text(`• ${rec}`);
    }
    doc.moveDown(1);

    doc.fillColor(BRAND_COLOR).fontSize(13).font("Helvetica-Bold").text("Account Security Checklist");
    doc.moveDown(0.3);
    doc
      .fillColor(MUTED_COLOR)
      .fontSize(9)
      .font("Helvetica")
      .text(`${record.checklistCompletionPercent}% complete`);
    doc.moveDown(0.3);
    for (const [key, label] of Object.entries(CHECKLIST_LABELS)) {
      const checked = record.checklist[key as keyof PasswordHistoryRecord["checklist"]];
      doc
        .fillColor(checked ? INK_COLOR : MUTED_COLOR)
        .fontSize(10)
        .font("Helvetica")
        .text(`${checked ? "☑" : "☐"} ${label}`);
    }

    doc.moveDown(1.5);
    doc
      .fillColor(MUTED_COLOR)
      .fontSize(8)
      .font("Helvetica")
      .text("Generated by CyberSentinel — an AI-powered cybersecurity assistant. This report never contains your actual password.", {
        align: "center",
      });

    doc.end();
  });
}
