import PDFDocument from "pdfkit";
import { PII_CATEGORY_LABELS } from "./piiDetection";
import { PRIVACY_RATING_LABELS } from "../utils/privacyScore";
import type { ResumePrivacyReport } from "../types";

const BRAND_COLOR = "#4F7CFF";
const MUTED_COLOR = "#5B6479";
const INK_COLOR = "#1A2233";

/**
 * Renders a ResumePrivacyReport to a PDF buffer entirely in memory —
 * pdfkit's PDFDocument is itself a readable stream, so we collect its
 * chunks rather than writing anything to disk.
 */
export function generateResumeReportPdf(report: ResumePrivacyReport): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 50 });
    const chunks: Buffer[] = [];

    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    // Header / branding
    doc.fillColor(BRAND_COLOR).fontSize(20).font("Helvetica-Bold").text("CyberSentinel");
    doc.fillColor(MUTED_COLOR).fontSize(10).font("Helvetica").text("Resume Privacy Report");
    doc.moveDown(1.5);

    // File + date
    doc.fillColor(INK_COLOR).fontSize(12).font("Helvetica-Bold").text(report.fileName);
    doc
      .fillColor(MUTED_COLOR)
      .fontSize(9)
      .font("Helvetica")
      .text(`Analyzed ${new Date(report.analyzedAt).toLocaleString()}`);
    doc.moveDown(1);

    // Score + rating
    doc
      .fillColor(BRAND_COLOR)
      .fontSize(28)
      .font("Helvetica-Bold")
      .text(`${report.privacyScore}/100`, { continued: true })
      .fillColor(MUTED_COLOR)
      .fontSize(12)
      .font("Helvetica")
      .text(`   ${PRIVACY_RATING_LABELS[report.privacyRating]}`);
    doc.moveDown(1);

    // AI review summary
    section(doc, "Summary");
    doc.fillColor(INK_COLOR).fontSize(10).font("Helvetica").text(report.aiReview.summary, { align: "left" });
    if (report.aiReview.risks.length > 0) {
      doc.moveDown(0.5);
      for (const risk of report.aiReview.risks) {
        bullet(doc, risk);
      }
    }
    doc.moveDown(1);

    // Detected information
    section(doc, "Detected Information");
    if (report.detected.length === 0) {
      doc.fillColor(MUTED_COLOR).fontSize(10).font("Helvetica").text("No personal information was detected.");
    } else {
      for (const item of report.detected) {
        doc
          .fillColor(INK_COLOR)
          .fontSize(10)
          .font("Helvetica-Bold")
          .text(`${PII_CATEGORY_LABELS[item.category]}: `, { continued: true })
          .font("Helvetica")
          .fillColor(MUTED_COLOR)
          .text(item.value);
      }
    }
    doc.moveDown(1);

    // Recommendations
    section(doc, "Recommendations");
    for (const rec of report.recommendations) {
      doc.fillColor(INK_COLOR).fontSize(10).font("Helvetica-Bold").text(`• ${rec.text}`);
      doc.fillColor(MUTED_COLOR).fontSize(9).font("Helvetica").text(rec.reason, { indent: 12 });
      doc.moveDown(0.4);
    }

    // Footer
    doc.moveDown(1);
    doc
      .fillColor(MUTED_COLOR)
      .fontSize(8)
      .font("Helvetica")
      .text("Generated by CyberSentinel — an AI-powered cybersecurity assistant.", { align: "center" });

    doc.end();
  });
}

function section(doc: PDFKit.PDFDocument, title: string): void {
  doc.fillColor(BRAND_COLOR).fontSize(13).font("Helvetica-Bold").text(title);
  doc.moveDown(0.3);
}

function bullet(doc: PDFKit.PDFDocument, text: string): void {
  doc.fillColor(INK_COLOR).fontSize(10).font("Helvetica").text(`• ${text}`);
}
